using webapi.db.attributes;

namespace webapi.dao
{
	[TableName("Events")]
	public class Event
	{
		public Event()  // Made public
		{
		}

		[PrimaryKey]
		public int EventId;

		[ColumnLength(100)]  // Fixed typo
		public string EventName = "";

		[ColumnLength(500)]  // Fixed typo
		public string Description = "";

		[ColumnLength(200)]  // Fixed typo
		public string Location = "";

		public int Capacity;
		public bool IsActive;

		[AutoGenerated]
		public DateTime CreatedDate;
	}
}