using webapi.db.attributes;

namespace webapi.dao
{
	[TableName("Events")]
	public class Event
	{
		public Event()
		{
		}

		[PrimaryKey]
		public ulong EventId = 0;

		[ColumnLength(100)]
		public string EventName = "";
		public DateTime EventDate = new();

		[ColumnLength(500)]
		public string Description = "";

		[ColumnLength(200)]
		public string Location = "";

		public ulong Capacity = 0;
		public bool IsActive = true;

		[AutoGenerated]
		public DateTime CreatedDate = new();
	}
}