using webapi.db.attributes;

namespace webapi.model
{

	public class Asociated
	{
		[PrimaryKey]
		[ColumnLength(9)]
		public ulong UserIdentity = 0;

		[ColumnLength(100)]
		public string FullName = "";

		[ColumnLength(320)]
		public string Email = "";

		[ColumnLength(20)]
		public string Phone = "";

		[AutoGenerated]
		public DateTime CreatedDate = new();
		
		[AutoGenerated]
		public DateTime ModifiedDate = new();
	}
}