using System.Runtime.Serialization;
using webapi.db.attributes;

namespace webapi.model
{

	[DataContract]
	public class Asociated
	{
		[PrimaryKey]
		[ColumnLength(9)]
		public ulong UserIdentity { get; set; } = 0;

		[ColumnLength(100)]
		public string FullName { get; set; } = "";

		[ColumnLength(320)]
		public string Email { get; set; } = "";

		[ColumnLength(20)]
		public string Phone { get; set; } = "";

		[AutoGenerated]
		public DateTime CreatedDate { get; set; } = new();

		[AutoGenerated]
		public DateTime ModifiedDate { get; set; } = new();
	}
}