using webapi.db.attributes;

namespace webapi.model
{


	public class Assistance
	{
		public enum State
		{
			[StringValue("P")]
			Proposed,  // proposed 
			[StringValue("C")]
			Confirmed, // confirmed
			[StringValue("R")]
			Rejected, // rejected
		}

		[PrimaryKey]
		[IdentityField]
		public ulong AssistanceId = 0;

		[ColumnLength(9)]
		public string UserIdentity = "";

		public ulong EventId;
		public State state = State.Proposed;
		[AutoGenerated]
		public DateTime ConfirmationDate = new();
	}
}