using System.Runtime.Serialization;
using System.Text.Json.Serialization;
using webapi.db.attributes;

namespace webapi.model
{

	[DataContract]
	public class Assistance
	{
		[JsonConverter(typeof(JsonStringEnumConverter))]
		public enum StateType
		{
			[StringValue("P")]
			Proposed,  // proposed 
			[StringValue("C")]
			Confirmed, // confirmed
			[StringValue("R")]
			Rejected, // rejected
		}

		[PrimaryKey]
		[IdentityField]
		public ulong AssistanceId { get; set; } = 0;

		[ColumnLength(9)]
		public string UserIdentity { get; set; } = "";

		public ulong EventId { get; set; } = 0;
		public StateType State { get; set; } = StateType.Proposed;
		[AutoGenerated]
		public DateTime ConfirmationDate { get; set; } = new();
	}
}