using System.Runtime.Serialization;
using webapi.db.attributes;

namespace webapi.model
{
	[TableName("Events")]
	[DataContract]
	public class Event
	{
		[PrimaryKey]
		[IdentityField]
		public ulong EventId { get; set; } = 0;

		[ColumnLength(100)]
		public string EventName { get; set; } = "";
		public DateTime EventDate { get; set; } = new();

		[ColumnLength(500)]
		public string Description { get; set; } = "";

		[ColumnLength(200)]
		public string Location { get; set; } = "";

		public ulong Capacity { get; set; } = 0;
		public bool IsActive { get; set; } = true;

		[AutoGenerated]
		public DateTime CreatedDate { get; set; } = new();
	}
}